Update ScheduleGame with gameguid, Homerunderby info with nongameguid…
zero-sum-seattle/python-mlb-statsapi pull request #199
Opened 2023-08-30 01:37 UTC by mgbeck002

…, and Game break fields

### Why

Getting errors with version 0.5.13 when getting schedule with an unexpected gameguid field. This identified other unexpected fields, in total:
- ScheduleGame.gameguid
- HomerunDerby.Info.nongameguid
- Pitchbreak.breakvertical, Pitchbreak.breakverticalinduced, Pitchbreak.breakhorizontal

### What

Add the following fields:
- ScheduleGame.gameguid
- HomerunDerby.Info.nongameguid
- Pitchbreak.breakvertical, Pitchbreak.breakverticalinduced, Pitchbreak.breakhorizontal

Updated the mock test data to reflect new output.

### Tests

Tested using mocked and external tests.

### Risk and impact

What is the risk level of the change and **why?**

- Minimal - tested with both external and updated mock data

What is the impact if something does go wrong with this PR? - minimal since these endpoints were having issues with version 0.5.13

2023-08-30 01:46 UTC, Mattsface commented
Thanks for the MR I will review when I get home tonight

2023-08-30 18:58 UTC, KCNilssen requested changes
Looks good to me. Thank you for adding the missing fields from the new MLB api update. Matt and I have been pretty busy last few weeks so much appreciated! Just address the issues with the mock json files and either Matt or myself will approve and merge :)

2023-08-30 18:58 UTC, KCNilssen commented on tests/mock_tests/mock_json/games/game.json
We don't need a full copy of the game endpoint for the mock json test. Previously this was cut down by hand to only have a few instances of each object so instead of a 50,000 line json file we had something that was only a few lines. 

A suggestion would be to find in the old mock json file where the new field is located and just populate those instances. Help keep the size down. Just a simple search for a field in the same struct should get you to that location. Let me know if you would like me to do this.

2023-08-30 18:58 UTC, KCNilssen commented on tests/mock_tests/mock_json/homerunderby/homerunderby.json
Same thing here like in the game mock json file

2023-08-30 18:58 UTC, KCNilssen commented on tests/mock_tests/mock_json/schedule/schedule_date.json
Same as the other mock json files.

2023-08-31 18:35 UTC, mgbeck002 commented
Thanks for the feedback. Those test files have been updated.

2023-08-31 23:35 UTC, Mattsface commented
Let's version bump it too 0.5.14 and call it good. Thanks for the PR.

2023-09-01 10:40 UTC, KCNilssen approved these changes
LGTM let's get it up

2023-09-01 10:40 UTC, merged